<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PurchaseSystem.Common\PurchaseSystem.Common.csproj" />
    <ProjectReference Include="..\PurchaseSystem.Data\PurchaseSystem.Data.csproj" />
    <ProjectReference Include="..\PurchaseSystem.Model\PurchaseSystem.Model.csproj" />
  </ItemGroup>

</Project>
